### ISSUE TITLE
[Suggestion] Compatibility with Villager Recruits

### ISSUE THREAD

**Issue by SlytherTheUndertaker** [VulpesStella/MrCrayfishGunMod#1]
Wouldn't it be cool to have them equip guns? There has been no mod (Except for TechGuns) that has done that, so far.

**Comment by VulpesStella** [comment]
Sounds interesting. Lemme try it :D

**Comment by VulpesStella** [comment]
> Wouldn't it be cool to have them equip guns? There has been no mod (Except for TechGuns) that has done that, so far.

@SlytherTheUndertaker  Good news, I've made it to be an independent mod named Gunners.
I'll upload a preview jar here soon, and then on CurseForge.

**Comment by MikhailTapio** [comment]
[UnzipMe.zip](https://github.com/MikhailTapio/MrCrayfishGunMod/files/13837191/UnzipMe.zip)

**Comment by MikhailTapio** [comment]
[UnzipMe.zip](https://github.com/MikhailTapio/MrCrayfishGunMod/files/13837249/UnzipMe.zip)

**Comment by MikhailTapio** [comment]
[UnzipMe.zip](https://github.com/MikhailTapio/MrCrayfishGunMod/files/13842202/UnzipMe.zip)

**Comment by VulpesStella** [comment]
[UnzipMe.zip](https://github.com/MikhailTapio/MrCrayfishGunMod/files/13842227/UnzipMe.zip)

**Comment by SlytherTheUndertaker** [comment]
Awesome! :D
However, after I put the mod on, there doesn't seem to be a category for the Gunners mod, and I couldn't find any item or spawn egg related to that mod. How that happened?
I just opened the zip file, placed the mod onto my mods folder in curseforge, and run the game to see if I have the mod on. That's why the mod didn't appear in the game.
Am I doing something wrong with it?

**Comment by VulpesStella** [comment]
> Awesome! :D However, after I put the mod on, there doesn't seem to be a category for the Gunners mod, and I couldn't find any item or spawn egg related to that mod. How that happened? I just opened the zip file, placed the mod onto my mods folder in curseforge, and run the game to see if I have the mod on. That's why the mod didn't appear in the game. Am I doing something wrong with it?

It's OK. Gunners doesn't add any new spawn egg or entity, it overhauls the crossbowman entity in Villager Recruits so you can equip him with guns from cgm :DDD

**Comment by SlytherTheUndertaker** [comment]
Sorry for late reply, but ah cool! :o
One more thing: Is it possible to make the mod compatible for Guard Villagers?

**Comment by VulpesStella** [comment]
> Sorry for late reply, but ah cool! :o One more thing: Is it possible to make the mod compatible for Guard Villagers?

I've tried, but the Guard Villagers' code was a bit confusing.

**Comment by VulpesStella** [comment]
I'll give another try now :D

**Comment by VulpesStella** [comment]
Implemented.
[UnzipMe.zip](https://github.com/MikhailTapio/MrCrayfishGunMod/files/14235984/UnzipMe.zip)

This is uploaded to CurseForge as well, see [here](https://www.curseforge.com/minecraft/mc-mods/villager-gunners).
