### ISSUE TITLE
Datapack Usage

### ISSUE THREAD

**Issue by dsarn** [VulpesStella/MrCrayfishGunMod#12]
Hey, I'm new to developing on minecraft and would love to know how to make an add-on for your mod. I understand if that's a lot to ask but at the very least, how can I make a datapack that tweaks your weapons damage/models? I've tried opening the jar and copying the data and mcmeta to create a datapack but my changes don't seem to be applying at all.

**Comment by VulpesStella** [comment]
Maybe try [this](https://github.com/Autovw/GunModDatapack)?

**Comment by dsarn** [comment]
tyty
