### ISSUE TITLE
[Question] How to make an addon

### ISSUE THREAD

**Issue by dsarn** [VulpesStella/MrCrayfishGunMod#14]
Any documentation on making addons? Still very new to github so not very good at navigating my apologies if I missed it somewhere.

**Comment by VulpesStella** [comment]
When you mention addons, do you want to talk about modifications to existing content or adding new firearms?
Adding new content requires writing a new mod.

**Comment by VulpesStella** [comment]
I'll close this for now, please reply if you have further questions.
