### ISSUE TITLE
[Feature Request] 角色移动下的子弹散布

### ISSUE THREAD

**Issue by juan-90s** [VulpesStella/MrCrayfishGunMod#15]
你好，请问是否有意为这个mod添加新特性：角色移动时射击精准度下降，子弹散布扩大。这个特性可以让gunmod更加真实，
目前这个mod没有这个特性。

具体代码逻辑部分在`src/main/java/com/mrcrayfish/guns/common/SpreadTracker.java` 下的第45行附近。

感谢

**Comment by VulpesStella** [comment]
之前有过同样的想法。但本模组在 CGM 官方版移植到 1.20.1 之前不计划加入新的核心特性。这个 issue 我先 pin 上，等官方版更新好了就可以开做（
