### ISSUE TITLE
ISSUE - Incompatible with Backpacked

### ISSUE THREAD

**Issue by landynmj** [VulpesStella/MrCrayfishGunMod#19]
When reloading, and not having enough bullets in survival mode, you will crash your client or be disconnected from server.

**Comment by VulpesStella** [comment]
Use Backpacked 2.2.5, for 3.0.0+s have incompatible changes.
I'll fix it in the next release, which will no longer be compatible with Backpacked 2.x.x.

**Comment by BlueYoshi68** [comment]
is this a joke 

![Image](https://github.com/user-attachments/assets/61605764-827b-44cd-902e-038b4b6433de)
