### ISSUE TITLE
[Bug?][Related with original CGM] Are dyed gun color differences and ammo reload animation fixed in your unofficial port?

### ISSUE THREAD

**Issue by chemlzh** [VulpesStella/MrCrayfishGunMod#2]
I have uploaded some issues on original CGM project page, here's the link:
我之前在CGM那里提交了Bug的反馈，但是至今为止Mr. Crayfish根本没有修复。其中一个，是制作枪械时，加入染料后得到的枪械，其颜色与CGM工作台渲染完全不同的Bug，另一个是装弹时子弹方向与枪管方向完全相反的Bug。

[Related to dyed gun color differences](https://github.com/MrCrayfish/MrCrayfishGunMod/issues/465)

[Related to ammo reload animation](https://github.com/MrCrayfish/MrCrayfishGunMod/issues/487)

I don't know if you can fix this rendering problem in your unofficial port.
希望作者大大能在非官方版里修复这两个问题，如果有可能的话，请提交到原模组的代码页，谢谢作者大大！

**Comment by VulpesStella** [comment]
装填已经在修了

**Comment by MikhailTapio** [comment]
![image](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/81358657/0113e090-8458-4d11-9213-6a2828c6f3f8)

**Comment by VulpesStella** [comment]
颜色我不太懂怎么处理，我觉得还是光照问题，然后也没想到怎么修。

**Comment by chemlzh** [comment]
Wait a minute, for shotgun buckshot, the direction is right, therefore you don't need to fix the buckshot shell reload. However, the direction of other reloaded cartridges are reversed, so you need to fix it.
等等，我看到你发的图了，其他枪械的子弹有问题，按你这么修改确实没错，但是**霰弹枪鹿弹**的装填方向是**不用改**的！因为鹿弹的黄色部分是它的底火，红色部分才是装弹头的！

附带几张图，从英文维基扒下来的

![image](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/32123043/d740e95c-8aa5-4e3b-8630-a1ffd74aa3d1)

![image](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/32123043/bf8b2787-164e-40f6-b3be-86c5f4b4f959)

**Comment by chemlzh** [comment]
感觉应该要分头处理：其他子弹是暗黄色的部分朝枪托，棕色/银色的弹头朝枪口；霰弹是黄色部分朝枪托，红色部分朝枪口。顺便，不知道榴弹装填的时候是不是也有这个问题，作者大大能否帮忙验证一下

**Comment by chemlzh** [comment]
> 颜色我不太懂怎么处理，我觉得还是光照问题，然后也没想到怎么修。

作者大大可以看看"WorkbenchScreen.java"的updateColor()函数部分，就是我在原issue那里截取的工作台上渲染染色后产物的程序

按说工作台显示的时候应该是调用这个程序，将原建模的颜色替换为染料的颜色，但是合成的时候，感觉变成原建模的颜色跟染料颜色融合平均了。而且这里补充一点，如果不加染料合成零件或枪械，然后在原版工作台上直接拿染料与白模零件合成，得到的颜色就是正常的染料显示的颜色，跟CGM工作台渲染的颜色一模一样

**Comment by VulpesStella** [comment]
> > 颜色我不太懂怎么处理，我觉得还是光照问题，然后也没想到怎么修。
> 
> 作者大大可以看看"WorkbenchScreen.java"的updateColor()函数部分，就是我在原issue那里截取的工作台上渲染染色后产物的程序
> 
> 按说工作台显示的时候应该是调用这个程序，将原建模的颜色替换为染料的颜色，但是合成的时候，感觉变成原建模的颜色跟染料颜色融合平均了。而且这里补充一点，如果不加染料合成零件或枪械，然后在原版工作台上直接拿染料与白模零件合成，得到的颜色就是正常的染料显示的颜色，跟CGM工作台渲染的颜色一模一样

你的意思是对于一个已经有颜色的物件，涂上新颜色应该直接覆盖原来的颜色而不是和原来的颜色混合吗？

**Comment by VulpesStella** [comment]
> Wait a minute, for shotgun buckshot, the direction is right, therefore you don't need to fix the buckshot shell reload. However, the direction of other reloaded cartridges are reversed, so you need to fix it. 等等，我看到你发的图了，其他枪械的子弹有问题，按你这么修改确实没错，但是**霰弹枪鹿弹**的装填方向是**不用改**的！因为鹿弹的黄色部分是它的底火，红色部分才是装弹头的！
> 
> 附带几张图，从英文维基扒下来的
> 
> ![image](https://private-user-images.githubusercontent.com/32123043/295106503-d740e95c-8aa5-4e3b-8630-a1ffd74aa3d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODcyMjIsIm5iZiI6MTcwNDc4NjkyMiwicGF0aCI6Ii8zMjEyMzA0My8yOTUxMDY1MDMtZDc0MGU5NWMtOGFhNS00ZTNiLTg2MzAtYTFmZmQ3NGFhM2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA3NTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MGVhZDg4MmRiYjM2OWYzMTE5NWUxMTMxNDg4OGIzNGQ5ZWRiNTQ1YWMzYjk2Y2FlYjY3MmQ2NTAwMTNmY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qsrURCZ2qbU_7sKBeqK3-jCMDjLZDSTLhtbUM8g-SZI)
> 
> ![image](https://private-user-images.githubusercontent.com/32123043/295106522-bf8b2787-164e-40f6-b3be-86c5f4b4f959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODcyMjIsIm5iZiI6MTcwNDc4NjkyMiwicGF0aCI6Ii8zMjEyMzA0My8yOTUxMDY1MjItYmY4YjI3ODctMTY0ZS00MGY2LWIzYmUtODZjNWY0YjRmOTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA3NTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMjU0MjIzZmYxNjgzY2JjMjA2ODg0ZjkyYmNmMTFmODcwNTQ3OGUwY2IyMWEyMDQ3M2IzZWYzNGUyMTc2ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.63dEnaIbgYzMSkGmHuI2EDt2a-mtgQI__Be-rHlv0ig)

如果这样的话代码部分也不用改了，把鹿弹的模型倒置一下就行了

**Comment by VulpesStella** [comment]
> > > 颜色我不太懂怎么处理，我觉得还是光照问题，然后也没想到怎么修。
> > 
> > 
> > 作者大大可以看看"WorkbenchScreen.java"的updateColor()函数部分，就是我在原issue那里截取的工作台上渲染染色后产物的程序
> > 按说工作台显示的时候应该是调用这个程序，将原建模的颜色替换为染料的颜色，但是合成的时候，感觉变成原建模的颜色跟染料颜色融合平均了。而且这里补充一点，如果不加染料合成零件或枪械，然后在原版工作台上直接拿染料与白模零件合成，得到的颜色就是正常的染料显示的颜色，跟CGM工作台渲染的颜色一模一样
> 
> 你的意思是对于一个已经有颜色的物件，涂上新颜色应该直接覆盖原来的颜色而不是和原来的颜色混合吗？

多颜色混合其实是符合原版设计的，所以不打算删。然后刚刚试着写了个把cgm物品丢进盛水炼药锅里洗掉颜色的功能，不知道算不算合理（
