### ISSUE TITLE
[MC 1.20.1] Broken knockback configs

### ISSUE THREAD

**Issue by Yokisan249** [VulpesStella/MrCrayfishGunMod#3]
In version 1.4.5 of the CGM port the knockback doesn't matter if it's disabled or set to 0.0, it's applied anyways as if it was still enabled. Kinda annoying when you are trying to land constant headshots but you miss the second shot because the mob got knocked back.

**Comment by VulpesStella** [comment]
This should be fixed in 1.4.6, now uploading.
