### ISSUE TITLE
[Bug/Upstream] Wrong death message

### ISSUE THREAD

**Issue by KLONOA9X6** [VulpesStella/MrCrayfishGunMod#4]
![image](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/95112579/0e2bb21e-31c9-4c0a-ace9-d672237ba209)

**Comment by KLONOA9X6** [comment]
When CGM was upgraded to 1.19.4, they abandoned the old Damage Type method in favor of Vanilla's damage_type. But there is no change to the language file.

**Comment by KLONOA9X6** [comment]
Upstream issue page：[#481](https://github.com/MrCrayfish/MrCrayfishGunMod/issues/481)

**Comment by VulpesStella** [comment]
Problem located. Will fix it in 1.4.7.
