### ISSUE TITLE
[Incompatibility] CMDCamera rolling Breaks with fork

### ISSUE THREAD

**Issue by guivnf** [VulpesStella/MrCrayfishGunMod#5]
So basically there's this mod called [CMDCam](https://www.curseforge.com/minecraft/mc-mods/cmdcam) that allows anyone to make some keyframes and things like that for cool takes on videos. When using both mods together (This fork, and CMDCam), the rolling camera feature provided by CMD cam when clicking "G" or "J" simply don't work. Everything else like zooming, keyframe assigning and such work just fine, but not the rotation/rolling your camera sideways 

Ver. - 1.20.1
CmdCam Ver. - [CMDCam_FORGE_v2.1.1_mc1.20.1]
CGM Unofficial Ver. - [CGM-Unofficial-1.4.7+Forge+1.20.1]
Forge Ver. - 47.2.1

Crash Logs/Logs: None as the issue does not provide any notable feedback on logs or any crashlogs, but i may provide if you ask for it anyway...

**Comment by VulpesStella** [comment]
Okay, I'll look into it soon. Did you check if it was a keybinding conflict issue?

**Comment by guivnf** [comment]
> Okay, I'll look into it soon. Did you check if it was a keybinding conflict issue?

Yes, made sure it wasn't a keybind conflict

**Comment by VulpesStella** [comment]
Can confirm. Currently have no idea how to fix :(

**Comment by guivnf** [comment]
> Can confirm. Currently have no idea how to fix :(

Thats fine, i can wait whatever time you need lmao. i can't report it to them as well if you need... But idk if they'd fix a port incompatibility

**Comment by VulpesStella** [comment]
> > Can confirm. Currently have no idea how to fix :(
> 
> Thats fine, i can wait whatever time you need lmao. i can't report it to them as well if you need... But idk if they'd fix a port incomatibility

Also tested in Forge1.19.2 + cgm-forge-1.19.2-1.3.7 + CMDCam-v2.0.15, G and J still not working. So it's like a problem from the original cgm (or CMDCam itself?).

**Comment by CreativeMD** [comment]
It's pretty obvious why it does happen, because this mod overwrites the roll: https://github.com/MikhailTapio/MrCrayfishGunMod/blob/62af0f5a9eb79aa36fb1677582c8791d6748c0b7/src/main/java/com/mrcrayfish/guns/client/handler/GunRenderingHandler.java#L838

It can be disabled in the config `cameraRollEffect`. Not sure what workaround could be implemented otherwise.

**Comment by VulpesStella** [comment]
> It's pretty obvious why it does happen, because this mod overwrites the roll:
> 
> https://github.com/MikhailTapio/MrCrayfishGunMod/blob/62af0f5a9eb79aa36fb1677582c8791d6748c0b7/src/main/java/com/mrcrayfish/guns/client/handler/GunRenderingHandler.java#L838
> 
> It can be disabled in the config `cameraRollEffect`. Not sure what workaround could be implemented otherwise.

Thx a lot :D

**Comment by VulpesStella** [comment]
@MetalKnight56 So I added a check for CMDCam in 1.20.1-1.4.12. If CMDCam has modified the roll, our camera roll effect will be disabled until the roll is reset.
