### ISSUE TITLE
Create Guns resource pack texture error

### ISSUE THREAD

**Issue by XBlayz** [VulpesStella/MrCrayfishGunMod#6]
The [Create Guns](https://www.curseforge.com/minecraft/texture-packs/create-guns) resource pack texture doesn't load properly, only the workbench is correctly loaded.

<img width="218" alt="Screenshot 2024-02-04 175018" src="https://github.com/MikhailTapio/MrCrayfishGunMod/assets/73166431/e317e959-17bd-4314-b700-a74dcaf5ceea">

What cloud it be? If I understand whats the problem i can probably fix it in the resource pack.

Info:
- Forge: `1.20.1 (v47.2.0)`
- Create Guns (resource pack): `Create+Guns+1.19`
- CGM Unofficial: `CGM-Unofficial-1.4.8+Forge+1.20.1`

**Comment by XBlayz** [comment]
I have found the problem, the folder that contain the textures is named `items` instead of `item` as it is in the mod.

But now there is another problem, the scopes doesn't work properly.
![2024-02-04_19 33 54](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/73166431/8d010247-d9aa-473f-9178-8cb943400499)
![2024-02-04_19 34 06](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/73166431/6958d6dd-b2df-4425-953b-13317f1c7d41)
![2024-02-04_19 34 19](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/73166431/9a105179-c0e2-417f-bf61-db0e87669f3b)

I think I need to change the position of the scope camera as the models are different but I don't know how to do it, could you help me fixing it?

**Comment by MikhailTapio** [comment]
It's affected by a mojang change in 1.19.3, see [Changes made in 1.19.3](https://www.minecraft.net/en-us/article/minecraft-java-edition-1-19-3):
To improve loading performance, block and item textures are now loaded before they are processed by block and item models
By default, textures not in the textures/item and textures/block directories will no longer be automatically recognized and will fail to load
Resource packs can now have configuration files, located in atlases directory, that control which images are included in the atlases.

**Comment by VulpesStella** [comment]
Read the Create Guns comments carefully and you'll see that the scope opacity issue has been around even as far back as version 1.19.
This is caused by the texture itself.
If you open the model with the texture via BlockBench, you'll notice some pixels just directly blocking the view. 
![image](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/81358657/fac527b7-0481-4a52-9727-84dc7c04e2a2)

Erasing them or making them translucent may help.

**Comment by XBlayz** [comment]
> Read the Create Guns comments carefully and you'll see that the scope opacity issue has been around even as far back as version 1.19.
> This is caused by the texture itself.
> If you open the model with the texture via BlockBench, you'll notice some pixels just directly blocking the view. 
> ![image](https://github.com/MikhailTapio/MrCrayfishGunMod/assets/81358657/fac527b7-0481-4a52-9727-84dc7c04e2a2)
> 
> Erasing them or making them translucent may help.

Yes, it seems like it's something that doesn't work in older versions either, I'll try to change the textures to make them transparent, thanks so much for your help.

**Comment by XBlayz** [comment]
I have modified the texture pack and now it works, it's not perfect by any stretch of the imagination, but now it's usable at least.

It's actually the first time I work on a texture pack using Blockbench, it's kinda cool but I'm still learning.

This is the texture pack if anyone is interested.
[Create+Guns+1.20.1 (v1.0).zip](https://github.com/MikhailTapio/MrCrayfishGunMod/files/14165435/Create%2BGuns%2B1.20.1.v1.0.zip)

**Comment by VulpesStella** [comment]
Another issue with this resourcepack is that there may be some display issues when other mod's gun models are also using textures from cgm. The best way to fix this is to rename all the textures in this resourcepack to prevent them from overwriting the original textures.

**Comment by JCS-3000** [comment]
[Create Guns 1.20.zip](https://github.com/user-attachments/files/15751194/Create.Guns.1.20.zip)

1.20 version with fixed, updated textures. Cheers.

**Comment by Rataticus** [comment]
> [Create Guns 1.20.zip](https://github.com/user-attachments/files/15751194/Create.Guns.1.20.zip)
> 
> 1.20 version with fixed, updated textures. Cheers.

where's the pack.mcmeta in the .zip though?

**Comment by Rataticus** [comment]
also, how do I get the create craftings?
because getting a minigun from the workbench with just a few iron seems kinda overpowered

**Comment by Barerock** [comment]
> [Create Guns 1.20.zip](https://github.com/user-attachments/files/15751194/Create.Guns.1.20.zip)
> 
> 1.20 version with fixed, updated textures. Cheers.

This doesn't work at all for me, neither textures nor data pack function. The pack doesn't show up in the menu before/after extraction.

**Comment by Barerock** [comment]
Dragging the 1.19.2 data and pack.mcmeta does make the datapack itself work, but all the 2D textures are broken still.

**Comment by Shaunster1** [comment]
Has there been a fix? cuz for me the only items that show up fine are the revolver, minigun, and workbench (I'm using 1.16.5 btw)

**Comment by Aterien** [comment]
Greetings y'all! I've managed to fix that issue when all 2d items like ammunition and mods used their 3d textures when displayed in inventory thus appeared broken. My workaround is creating a folder "3d_textures" at \assets\cgm\textures\item with all textures used in actual 3d models (This exact folder is present in the original resourcepack for 1.19) and changing some ..._3d.json files at \assets\cgm\models\item to use textures from said folder. 2d sprites are now at \assets\cgm\textures\item.
Works on my side but I'm no expert in creating addons.

[Create guns 1.20.1 fixed (kinda).zip](https://github.com/user-attachments/files/16778595/Create.guns.1.20.1.fixed.kinda.zip)

Please remember that for the addon to work correctly you need to place this .zip file in your resourcepacks folder as well as in your world's datapacks folder.
