### ISSUE TITLE
Working together my New Project 

### ISSUE THREAD

**Issue by Argoswilliams57** [VulpesStella/MrCrayfishGunMod#7]
Hello how are you , I am Stabilizer king from your Curseforge page

So , I am a Minecraft developer too (well sort of) i made My Addon Stabx Modern guns and also updated to 1.20.1 using your Unofficial Ported CGM as a Required Dependency and I am very greatful for that , also i was wondering will you be working with me on My New Fork of Mrcrayfish gun mod I know 3d Modelling Sound design , also Animating so  how about you and me work together on a animated version of My Independent warfare Mod it will be Fork Of Mrcrayfishes gun mod but Animated I really wanted that for  so long finally i am able to reach out to you 

so what do you say

**Comment by Argoswilliams57** [comment]
Also i am very aware of the kids in the mrcrayfish server Calling you a theif   while it is not your fault and it is very dissapointing that they dont have better anything to do rather than shitting on other people who do a great job for us Gun mod Community to enjoy the mod 
Funny thing is that same thing happened to me too and yeah they also called me a theif and accusing me for stealing a stupid code which i Never did in the past all i was complying with the Lisence and portraying me as a bad person while actually i am not this hurts me more than ever that I had to leave the Mrcrayfish discord for good so i dont get myself  in another panic attacks seeing their bad messages shitting on my mod or on me

**Comment by VulpesStella** [comment]
Hello! Glad to see you say these! Since I'm nearing graduation (preparing my thesis) and I'm self-conscious about my rather average programming skills, I may not be able to provide long-lasting, effective help. If you have any specific needs you can contact me, and I can also try to put you in touch with some developers I know well, thanks!

**Comment by Argoswilliams57** [comment]
Thank you soo much so ,which is the best app  a you are using where  I can contact you having a Real time conversation , i belive in you you can that with the help of geckolib or Azure lib we can achieve the Same like timeless and classics But non hyper realistic 
Only Basic guns  animations  , firing , Walking , sprinting , Inspect  and Empty Inspect when the adsing also ADS Firing too 
, will be needing  any way which messaging yo use the most you can add me there and hit me up with other devs
