### ISSUE TITLE
Can you fix issue #4 for 1.19.4?

### ISSUE THREAD

**Issue by ghost** [VulpesStella/MrCrayfishGunMod#8]
Can you please fix #4 for 1.19.4? Thanks!

**Comment by VulpesStella** [comment]
Okay, I can make a mixin to implement the fix, but not in this project.

**Comment by VulpesStella** [comment]
> Can you please fix #4 for 1.19.4? Thanks!

[UnzipMe.zip](https://github.com/MikhailTapio/MrCrayfishGunMod/files/14544990/UnzipMe.zip)

Have a try :)

**Comment by ghost** [comment]
thanks!
